config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # root to: 'pages#home'
  resources :tickets do
    resources :orders, only: %i[new create]
  end
  root to: 'tickets#index'

  resources :orders, only: %i[index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :ticket
  validates :credcard, presence: true
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :user
  has_one :order, dependent: :destroy
  has_one_attached :photo
  validates :event_name, presence: true
  validates :event_price, presence: true
  validates :event_date, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tickets, dependent: :destroy
  has_many :orders
  has_one_attached :avatar
  validates :name, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :avatar])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = policy_scope(Order).order(created_at: :desc)
    @orders = Order.where(user: current_user)
    authorize @orders
  end

  def new
    @ticket = Ticket.find(params[:ticket_id])
    @order = Order.new
    authorize @order
  end

  def create
    @ticket = Ticket.find(params[:ticket_id])
    @order = Order.new(order_params)
    authorize @order
    @order.ticket = @ticket
    @order.user = current_user
    if @order.save
      @ticket.update(available: false)
      redirect_to root_path, notice: 'Ticket adquirido com sucesso!'
    else
      render :new
    end
  end

  private

  def order_params
    params.require(:order).permit(:credcard, :user_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @tickets = policy_scope(Ticket).order(created_at: :desc)
    authorize @tickets
  end

  def new
    @ticket = Ticket.new
    authorize @ticket
  end

  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.user = current_user

    authorize @ticket

    if @ticket.save
      redirect_to tickets_path(@ticket)
    else
      render :new
    end
  end

  def edit
    @ticket = Ticket.find(params[:id])
    authorize @ticket
  end

  def update
    @ticket = Ticket.find(params[:id])
    authorize @ticket
    if @ticket.update(ticket_params)
      redirect_to @ticket, notice: 'Seu ticket foi atualizado!'
    else
      render :edit
    end
  end

  def destroy
    @ticket = Ticket.find(params[:id])
    @ticket.destroy
    redirect_to tickets_path(@ticket)
    authorize @ticket
  end

  def show
    @ticket = Ticket.find(params[:id])
    authorize @ticket
  end

  private

  def ticket_params
    params.require(:ticket).permit(:event_price, :event_name, :event_date, :user_id, :photo, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cambista</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/orders/index.html.erb
<div class="container mb-3">
  <% @orders.each do |order| %>
    <div class="card-product">
      <%= image_tag (order.ticket.photo.attached? ? cl_image_path(order.ticket.photo.key, crop: :thumb) : asset_path("blank.png")) %>
      <div class="content">
        <div class="description">
          <div class="d-flex justify-content-between ">
            <h3><%= order.ticket.event_name.to_s.capitalize %></h3>
            <p>Data: <%= order.ticket.event_date %></p>
          </div>
          <p><%= order.ticket.description[..300] %>...</p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/orders/new.html.erb
<div class="container col-sm-8 text-center">

  <h2>Estamos quase finalizando sua compra...</h2>

  <%= simple_form_for [@ticket, @order] do |f| %>
  <div class="form-inputs mt-4 col-md-6 offset-md-3">
    <%= f.input :credcard, label: 'Cartão de crédito' %>
      <div class="form-actions">
        <%= f.button :submit, 'Comprar!', class: 'btn-registrar' %>
      </div>
  </div>
  <% end %>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-copyright">
   <p>Projeto feito com <i class="fas fa-heart"></i> por Igor, Lídia, Thiago e Mateus!</p>
  </div>
  <div class="footer-photos">
    <%= image_tag "igor.jpg", class: "rounded-circle" %>
    <%= image_tag "lidia.jpg", class: "rounded-circle"%>
    <%= image_tag "thiago.jpg", class: "rounded-circle" %>
    <%= image_tag "mateus.jpg", class: "rounded-circle" %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-cambista">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand mx-5" do %>
      <%= image_tag "logo.png", class: "w-101 h-100" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
          <%if current_user.avatar.attached? %>
            <%= cl_image_tag current_user.avatar.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= image_tag "avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <% end %>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "Meus ingressos", orders_path, class: "dropdown-item" %>
                <%= link_to "Sair", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Registrar", new_user_registration_path, class: "btn btn-registrar-navbar mx-2" %>
          </li>
           <li class="nav-item">
            <%= link_to "Entrar", new_user_session_path, class: "btn btn-entrar-navbar" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/tickets/edit.html.erb
<div class="container col-sm-8 text-center">

  <h2>Editar seu ingresso</h2>

    <%= simple_form_for @ticket do |f| %>
      <div class="form-inputs mt-4 col-md-6 offset-md-3">
        <%= f.input :event_name, label: "Nome do evento" %>
        <%= f.input :event_price, label: "Preço" %>
        <%= f.input :description, label: "Descrição", as: :text, :input_html => { :cols => 5, :rows => 5 } %>
        <%= f.input :event_date, label: "Data" %>
        <%= f.input :photo, label: "Foto do Evento", as: :file %>
          <div class="form-actions">
          <%= f.button :submit, 'Salvar alteração!', class: 'mt-3 btn-registrar-navbar' %>
          </div>
      </div>
    <% end %>
</div>

app/views/tickets/index.html.erb
<div class="container my-5">
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2340&q=80);">
    <h1 class="text-center">Ingressos disponíveis</h1>
    <%= link_to "Venda seu ingresso", new_ticket_path, class: "btn btn-venda-seu-ingresso" %>
  </div>
  <div class="cards my-5">
    <% if @tickets.length > 0 %>
      <% @tickets.each do |ticket| %>
        <%= link_to ticket_path(ticket), class: "text-decoration-none" do %>
          <div class="card-ticket">
            <%= image_tag (ticket.photo.attached? ? cl_image_path(ticket.photo.key, crop: :thumb) : asset_path("blank.png")) %>
            <div class="card-ticket-infos">
              <div>
                <h2><%= ticket.event_name %></h2>
                <p><strong>Vendido por:</strong> <%= ticket.user.name %> </p>
                <p><strong>Data do evento:</strong> <%= ticket.event_date %></p>
              </div>
              <h2 class="card-ticket-pricing">R$ <%= ticket.event_price %></h2>
            </div>
          </div>
        <% end %>
      <% end %>
    <% else %>
      <p>Nao há ingressos disponíveis para venda</p>
    <% end %>
  </div>
</div>

app/views/tickets/new.html.erb
<div class="container col-sm-8 text-center">

  <div class="banner justify-content-center" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1514525253161-7a46d19cd819?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1374&q=80);">
   <h2 class="text-center">Venda seu ingresso na cambista</h2>
  </div>


    <%= simple_form_for @ticket do |f| %>
      <div class="form-inputs mt-4 col-md-6 offset-md-3">
        <%= f.input :event_name, label: "Nome do evento" %>
        <%= f.input :event_price, label: "Preço" %>
        <%= f.input :description, label: "Descrição", as: :text, :input_html => { :cols => 5, :rows => 5 } %>
        <%= f.input :event_date, label: "Data" %>
        <%= f.input :photo, label: "Foto do Evento", as: :file %>
          <div class="form-actions">
          <%= f.button :submit, 'Vender ingresso!', class: 'mt-3 btn-registrar-navbar' %>
          </div>
      </div>
    <% end %>
</div>

app/views/tickets/show.html.erb
<div class="container content-page mt-5">
  <div class="row">
    <div class="img-show col-12 col-lg-6">
      <%= image_tag (@ticket.photo.attached? ? cl_image_path(@ticket.photo.key, crop: :thumb) : asset_path("blank.png")), class: "banner-ticket" %>
    </div>
    <div class="p-5 col-12 col-lg-6">
      <div class="ml-5 my-5">
        <p>Data do evento: <%= @ticket.event_date %></p>
      <hr>
        <h1 class=""><%= @ticket.event_name.to_s.capitalize %></h1>
      <p class=""><%= @ticket.description %></p>
      </div>
      <h2 class="mb-5">R$ <%= @ticket.event_price %></h2>
      <div class="d-flex gap-2 justify-content-end">
        <% if @ticket.user == current_user %>
          <%= link_to 'Editar', edit_ticket_path(@ticket), class: 'btn btn-registrar-navbar' %>
          <%= link_to 'Deletar', ticket_path(@ticket), method: :delete, data: {confirm: "Voce tem certeza que quer apagar?"}, class: 'btn btn btn-registrar-navbar' %>
        <% else %>
          <%= link_to 'Comprar ingresso', new_ticket_order_path(@ticket), class: 'btn btn-registrar-navbar' %>
        <% end %>
      </div>
    </div>
  </div>
</div>